flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/bar_plot_default.R
  - R/compute_summary_of_differences.R
  - R/isnulllist.R
  - R/fonction_groupement.R
  - R/knitting_plots_subfigures.R
  - R/read_data.R
  - R/comparison-between-multiple-cwp-datasets.R
  tests:
  - tests/testthat/test-read_data.R
  - tests/testthat/test-fonction_groupement.R
  vignettes: vignettes/first.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: First
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
