flat_additional.Rmd:
  path: dev/flat_additional.Rmd
  state: active
  R: R/my_fun.R
  tests: tests/testthat/test-my_fun.R
  vignettes: vignettes/go-further.Rmd
  inflate:
    flat_file: dev/flat_additional.Rmd
    vignette_name: Go further
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/bar_plot_default.R
  - R/cat_title.R
  - R/compute_summary_of_differences.R
  - R/isnulllist.R
  - R/fonction_empreinte_spatiale.R
  - R/fonction_groupement.R
  - R/function_multiple_comparison.R
  - R/generate_plot.R
  - R/is_ggplot.R
  - R/knitting_plots_subfigures.R
  - R/pie_chart_2_default.R
  - R/qflextable2.R
  - R/read_data.R
  - R/render_subfigures.R
  - R/save_image.R
  - R/separate_chunks_and_text.R
  tests:
  - tests/testthat/test-read_data.R
  - tests/testthat/test-isnulllist.R
  - tests/testthat/test-cat_title.R
  - tests/testthat/test-is_ggplot.R
  - tests/testthat/test-qflextable2.R
  - tests/testthat/test-function_multiple_comparison.R
  - tests/testthat/test-compute_summary_of_differences.R
  - tests/testthat/test-separate_chunks_and_text.R
  vignettes: vignettes/first.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: First
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
