```{r results='asis'}

if (!is.null(all_list)) {
  cat("# Detail of all the steps of treatment of the data\n\n",
      "For each treatment on the data, we provide a summary of what has been added, removed or transformed. ",
      "This allows to see where major changes occur for specific data needs.\n\n")
  
}
```


```{r processallandHIDe, echo=FALSE, results='hide'}

# Function to process each list item and knit the child document
process_list_item <- function(list_item, template) {
  if(is.character(list_item)){
    list_item <- qs::qread(list_item)
  }
  if (!(length(list_item) == 1 && is.na(list_item))) {
  child_env_result <- list2env(list_item, new.env())
  
  res <- knitr::knit_child(template, envir = child_env_result, quiet = TRUE)
  rm(child_env_result)
  gc()
  return(res)
  }
}

# Iterate over all items in all_list and process each dataset

if(!is.null(all_list)){
results <- lapply(all_list, process_list_item, template = system.file("rmd/comparison.Rmd", package = "CWP.dataset"))

# Perform garbage collection
gc()
}
results <- Filter(Negate(is.null), results)
```


```{r unlistallcomp,echo=FALSE, results='asis'}

if(!is.null(all_list)){
cat(unlist(results), sep =  "\\clearpage")
}

```

```{r include=FALSE}

if(!is.null(all_list)){
rm(results)
gc()
}

```
