---
title: "Setup_markdown"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "BastienGrasset"
output: html_document
---


```{r include=FALSE}

knitr::opts_chunk$set(duplicate.label = "allow")
# Packages the report cannot be rendered without
required_packages <- c("dplyr", "flextable", "stringr", "bookdown", "data.table", "ggplot2", "knitr", "sf", "tidyr", "futile.logger")

lapply(required_packages, function(pkg) {
  library(pkg, character.only = TRUE)
})

# Packages only needed by optional features (PDF output, tmap maps, ...): attached when installed
optional_packages <- c("tinytex", "tmap", "kableExtra", "webshot")

lapply(optional_packages, function(pkg) {
  if (requireNamespace(pkg, quietly = TRUE)) library(pkg, character.only = TRUE)
})

require(CWP.dataset)
base::options(scipen=9999)

if(!exists("plotting_type") | !knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"){
  plotting_type  <- "plot"  
} else{
plotting_type <- plotting_type}
if (requireNamespace("tmap", quietly = TRUE)) tmap::tmap_mode(plotting_type)

knitr::opts_chunk$set(echo = FALSE)

```


```{r message=FALSE, warning=FALSE, include=FALSE}

set_flextable_defaults(
  font.size = 10,
  font.color = "black",
  digits = 2,
  theme_fun = "theme_box"
)


#set the dataset caption styling
knitr::opts_chunk$set(tab.cap.pre = "Table ", tab.cap.sep = ": ")

#set the dataset caption styling
autonum <- officer::run_autonum(seq_id = "tab", bkm = "TC1", bkm_all = TRUE) # number the table, bkm (bookmark) is important as the cross-referencing is done using the bookmark


```
