# Workflow GitHub Actions pour R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y qpdf make libsodium-dev libicu-dev libxml2-dev \
            libssl-dev pandoc librdf0-dev libnode-dev libcurl4-gnutls-dev \
            libmysqlclient-dev libpq-dev zlib1g-dev make libjq-dev \
            libsecret-1-dev libnetcdf-dev libpng-dev libgdal-dev gdal-bin \
            libgeos-dev libproj-dev libsqlite3-dev libudunits2-dev

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Run R CMD check (ignore warnings)
        run: |
          R CMD build .
          R CMD check --no-manual --compact-vignettes=gs+qpdf *.tar.gz || true
